name: Deploy HireHub to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd Hirehub || git clone https://github.com/BabSatya/Hirehub.git && cd Hirehub
          git pull origin main
          
          # Backend setup
          cd Backend
          npm install
          pm2 restart backend || pm2 start server.js --name backend

          # Frontend setup
          cd ../Frontend
          npm install
          npm run build

          # Restart Nginx to load new build
          sudo systemctl restart nginx
